[toolchain]
anchor_version = "0.31.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
vela_protocol = "22jxKPxpHpHPA1aXjczuyVwVj3GPS5CBKz98dQNPAGjP"
mock_kamino = "MoCKKamino111111111111111111111111111111111"
mock_ondo = "MoCKondo11111111111111111111111111111111111"

[programs.devnet]
vela_protocol = "22jxKPxpHpHPA1aXjczuyVwVj3GPS5CBKz98dQNPAGjP"
mock_kamino = "MoCKKamino111111111111111111111111111111111"
mock_ondo = "MoCKondo11111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
