[toolchain]
anchor_version = "0.30.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
vela_protocol = "vELaP4bE8YfS2PqNXZj5m3tEwP6dZk3P"

[programs.devnet]
vela_protocol = "vELaP4bE8YfS2PqNXZj5m3tEwP6dZk3P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
